services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_CONTAINER_NAME}
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: ${DATABASE_CONTAINER_NAME}
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      PGPORT: ${DATABASE_PORT}
      PGDATA: /data/postgres
    volumes:
      - ./database:/data/postgres
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    restart: unless-stopped